metaswitch/common/logging_config.py, metaswitch/common/phonenumber_utils.py, metaswitch/common/tornado_utils.py, metaswitch/common/utils.py, setup.py
python-common is quite closely tied to Ellis and Crest. This PR makes it less so.
Specifically, I've:
* dropped the setup.py dependency on tornado
* split Tornado- and libphonenumber-related utilities out, so that it's possible to import 'utils' without having those
* removed configure_logging's expectation that we have a settings.py module, so it can be set up from command-line arguments
The resulting model is a bit closer to cpp-common - where things like diameterstack.cpp expect you to have freeDiameter, but it's the parent application's job to build and link freeDiameter. Likewise, tornado_utils.py depends on Tornado, but it's Crest's/Ellis' responsibility to install Tornado before using tornado_utils.
=> [Reviewer: Alex] Make python-common more generic

metaswitch/common/alarms.py, metaswitch/common/comm_monitor.py, metaswitch/common/monotonic_time.py, metaswitch/common/test/comm_monitor.py
This also pulls in alarms code from clearwater-etcd and CLOCK_MONOTONIC code from Crest.
=> [Reviewer: Ellie] Add Python communication monitor

metaswitch/common/alarms.py, metaswitch/common/comm_monitor.py, setup.py
Can you briefly review these fixes from alarms live testing? I've:
* moved some alarms setup code to where the issue_alarm function is first called (so that it happens after the logging code is started)
* added some more logs
* given python-common a dependency on pyzmq
=> [Reviewer: Ellie] Alarms live test fixes

Makefile
@rkd-msw recently (d0a33f97) changed the `CC` complier used to build python packages (so he could provide `cpp-common`'s `include` directory) but as a side effect, he switched us to compiling the code with `g++` rather than `gcc`.
This PR changes us back so we use the normal `${CC}` compiler and just add the extra flag.  This is the root cause of the current Ellis build failure on Jenkins.  Tested on the Jenkins server to ensure this resolves the issue.
=> Reviewer Matt - Use C compiler to compile C code

Makefile
I've fixed up the Makefile to clean out old eggs, allowing my environment to build after your recent version pinning. This isn't the full solution - we should be smart about when we do this rather than forcing users to run `make clean` when we change dependency versions.
=> [Reviewer Ellie] Build error

metaswitch/common/alarms.py, metaswitch/common/test/test_alarms.py
Chris,
On nodes with multiple cluster-manager plugins, clearwater-cluster-manager is failing to start with the stack below. I believe this should fix it, and I'm just testing now. Does it look sensible to you?
```
09-03-2016 14:28:30.180 UTC ERROR logging_config.py:107 (thread MainThread): Uncaught exception:
Exception: UnboundLocalError
Detail: local variable 'should_start' referenced before assignment
Traceback:
File "/usr/share/clearwater/bin/clearwater-cluster-manager", line 40, in <module>
main(sys.argv[1:])
File "build_clustermgr/bdist.linux-x86_64/egg/metaswitch/clearwater/cluster_manager/main.py", line 194, in main
syncer = EtcdSynchronizer(plugin, sig_ip, etcd_ip=mgmt_ip)
File "build_clustermgr/bdist.linux-x86_64/egg/metaswitch/clearwater/cluster_manager/etcd_synchronizer.py", …
```
=> Reviewer CNE: Define should_start

Makefile, metaswitch/common/alarms.py
Starts Python alarms in `None` state. Checks that an alarm is not in `None` state before resyncing.
Also has a couple of fixes in the Makefile to ensure the right version of setuptools is installed, and to stop errors in make clean when some objects cannot be found to be deleted.
=> [Reviewer: Rob] Alarm reliability

metaswitch/common/test/utils.py, metaswitch/common/utils.py
This commonalizes some of the function we have in clearwater-etcd and crest, so we can use it everywhere.
Typical call is:
```python
logging.configure_logging(utils.map_clearwater_log_level(args.log_level), ....)
```
=> [Reviewer: Ellie] Map log levels from Clearwater to logging module

Makefile
I hit an instance where, on a specific box for whatever reason, searching for 17.1 resulted in getting version 32.1.3 instead, which resulted in build issues. Changing to version 24 fixes this.
=> [Reviewer: EM] Update setuptools version from 17.1 to 24

Makefile, metaswitch/common/alarms_parser.py, metaswitch/common/alarms_to_dita.py, metaswitch/common/dita_content.py, metaswitch/common/stats_to_dita.py, metaswitch/common/test/test_valid_alarms.dita
Ellie, you reviewed @MatMeredith 's original changes here. Can you please review this too?
At request from docs group:
* Changed column widths to stop OIDs overrunning into the next column.
* Use thead for the title rows of tables.
* Capitalized initialisms in column titles.
* Use * instead of % in column widths for compatibility with tools used
by docs group.
For easier-to-use docs, include entire OID in alarm tables.
Fixed up PEP8 in the files I touched, and fixed up subprocess to use safer semantics.
=> [Reviewer: Mat] - Tweaks to docs autogen code.

Makefile
The --no-download flag was only introduced to virtualenv in V14.0.0, so
using it breaks the makefile with older versions.
=> [Reviewer: None] Revert change to use --no-download flag.

metaswitch/common/alarms_parser.py, metaswitch/common/alarms_to_dita.py
As preparation to split out all docs tools to https://github.com/Metaswitch/clearwater-docs-tools, this pull request refactors `alarms_to_dita` and `write_dita_file` from `alarms_parser` to `alarms_to_dita`, so that the module `dita_content` doesn't get imported anywhere else than the actual docs tool scripts.
=> Refactor dita function from alarms_parser

metaswitch/common/alarms_parser.py, metaswitch/common/alarms_to_dita.py
Reverts Metaswitch/python-common#85.
The build http://repo.cw-ngv.com:8080/job/python-common/220/console broke with:
```
cc -Icpp-common/include -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_cffi.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_cffi.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_cffi.o -lclearwaterutils -lstdc++ -o /var/lib/jenkins/slave/workspace/python-common/metaswitch/common/_cffi.so …
```
=> Revert "Refactor dita function from alarms_parser"

metaswitch/common/alarms_parser.py, metaswitch/common/generate_stats_csv.py, metaswitch/common/mib.py
Unfortunately we broke the python-common build last week by updating some doc generation scripts. The build failed because of some flake8 problems that sneaked into `mib.py`: http://repo.cw-ngv.com:8080/job/python-common/221/changes. 
I have fixed up the `mib.py` flake8 errors and spotted while doing this that `alarms_parser.py` includes a bug (duplicated Python dictionary key) that flake8 spotted when running it locally on my checkout. I have fixed this as well after talking with MGM and deleted the unused key. I have checked that the script still produces the exact same output as before which the docs team are apparently happy with.
Additionally I've added a comment to `generate_stats_csv.py` describing how the script handles duplicates in the input MIB files.
Running `make verify` on …
=> git Flake8 fixes for mib.py

metaswitch/common/alarms_parser.py, metaswitch/common/generate_stats_csv.py, metaswitch/common/mib.py, metaswitch/common/stats_to_dita.py
This pull request is fixing https://github.com/Metaswitch/clearwater-issues/issues/2091. The problem was that there wasn't clear ownership of the COLUMNS in `stats_to_dita.py` which got implicitly modified by the `Statistics` class. I have fixed this up by passing a copy of `COLUMNS` rather than `COLUMNS` itself to the initializer of a `Statistics` object.
=> Stats to DITA fix

metaswitch/common/utils.py
This PR moves the TERM and QUIT signal handlers into common code so that they can be called from any of the etcd based processes.
To use the QUIT handler, a process must implement the leave_cluster() method. Note that only cluster manager only currently does this. This makes me thing that maybe we shouldn't commonalise it. Thoughts?
=> [Reviewer: EM] Commonalise TERM and QUIT handlers

setup.py
I pinned all the python packages to the versions found in the build logs (for the last successful build).
The exception is cffi, which I pinned to a more up-to-date version to allow Crest to build again.
I also added downstream dependencies in.
I found these by using the console output from the build server, and also by seeing what packages were present in the .eggs directory created when the repo is made.
I've spun up a deployment including these changes using chef, and it build correctly.
=> Pin python dependencies in python-common

metaswitch/common/mib.py
Hi Chris, as discussed, here is a short addition to `mib.py` making sure to not crash with `OSError: [Errno 2] No such file or directory` if `snmptranslate` is not installed and to provide a more useful exception.
=> Add error handling if snmptranslate is not installed

metaswitch/common/stats_to_dita.py
We were sorting OIDs as dumb strings. We should sort them
lexicographically by numeric component so that they appear in a
sensible order in the docs.
=> [Reviewer: RJW2] Sort OIDs lexicographically.

Makefile
Seb,
To make the build less reliant on the environment, it'd be nice to use a version of flake8 from the virtual env, rather than from the global environment for `make verify` and friends.
=> [Reviewer: Seb] Use local flake8 for make verify & style

.gitignore, Makefile, requirements-test.txt, requirements.txt, setup.py
- Use wheels instead of eggs
- Use requirements.txt to track dependencies instead of setup.py
=> [Reviewer: Chris] Fix python packaging

Makefile
If Python gives us an old version of pip in the environment, it fails with the following, so enforce a newer version:
```
Running setup.py bdist_wheel for metaswitchcommon 
Destination directory: /home/user/src/python-common/.wheelhouse 
Successfully built cffi monotonic pycparser pycrypto pyzmq metaswitchcommon 
Cleaning up... 
/home/user/src/python-common/_env/bin/pip install --compile --no-index --upgrade --pre --force-reinstall --find-links=.wheelhouse metaswitchcommon 
Ignoring indexes: https://pypi.python.org/simple/ 
Downloading/unpacking metaswitchcommon 
Could not find any downloads that satisfy the requirement metaswitchcommon 
Cleaning up... 
No distributions at all found for metaswitchcommon
```
=> [No reviewer] Enforce a later version of pip

requirements.txt
We need to install later versions of pip and wheel in order to be able to install the rest of the wheels (particularly ones with embedded C - e.g. cffi).
This pins updated versions of the wheels. There's co-requisite changes to install these in each rep which uses python-common sadly.
=> [Reviewer: Seb] Pin and require versions of pip and wheel

metaswitch/common/logging_config.py
Simple change of `datetime.fromtimestamp` to `datetime.utcfromtimestamp`
Tested live on a system running in a different timezone (CEST), and the queue-manager_<timestamp> log had the correct UTC time in it. This matches changes in https://github.com/Metaswitch/clearwater-etcd/pull/499 so we are more consistent
=> [No reviewer] Use UTC for python logfile names

.gitignore, Makefile
Changes to use: https://github.com/Metaswitch/clearwater-build-infra/pull/69
We still need a separate `build_common_wheel` target as that's used by etcd (and anything else that uses python-common).
Other than that, it's a fairly straightforward usage of the new common infra.
=> [Reviewer: Richard] Common python build infra

metaswitch/common/logging_config.py, metaswitch/common/test/test_logging.py
In syslog, the tag is the part of the message preceding the first semi-colon character. This change modifies the way we send syslogs so that any one who runs `configure_syslog()` must supply a tag that all messages will use. This makes it much easier to filter the messages with syslog configuration.
=> [Reviewer: Seb] Modifies the syslog logging code to support tags

Makefile, metaswitch/common/utils.py
Leave out MD5 from bandit analysis as it's required by SIP spec.
=> Fix bandit medium issues
