Metaswitch/python-common

metaswitch/common/logging_config.py
Rob, can you review this change to move the logging function into python common and use UTC for the logs
Part of the fix for #8
=> [Reviewer: Rob] Move logging_config to common

metaswitch/common/logging_config.py
This is a bunch of changes to Python logging that I've been working on. Specifically, it:
* makes Python log files have a timestamped name rotated every hour, like C++ log files
* brings the log format into line with the C++ log format (e.g. date presentation)
* sets the log file mode to 644 rather than 777
* adds an exception hook to log Python exceptions, so you don't need to look in the separate ellis-0-err.log file (which is where all the stderr output goes).
I've done some basic testing, but before merging, I'll spin up a homestead-prov node with this change, leave it running for an hour, and check that the files roll over.
=> [Reviewer:Ellie] Bring Python log files in line with C++ ones

metaswitch/common/comm_monitor.py, metaswitch/common/pdlogs.py
Graeme, can you review this change to add PD logs to the new python communication monitor. 
Tested live
=> [Reviewer: Graeme] Add pd logs for comm monitor

metaswitch/common/alarms_parser.py, metaswitch/common/alarms_writer.py, metaswitch/common/test/alarms_parser.py, metaswitch/common/test/test_invalid_cause.json, metaswitch/common/test/test_missing_non_cleared.json, metaswitch/common/test/test_valid_alarms.json
Rob, can you please review this script to parse an alarms file and write out the alarm IDs
=> [Reviewer: Rob] Add python alarms parser

.gitignore, Makefile, metaswitch/common/comm_monitor.py, metaswitch/common/test/alarms_parser.py, metaswitch/common/test/pdlogs.py, metaswitch/common/utils.py
Adds a make verify target and fixes the warnings
=> [Reviewer: Rob] Add verify target and fix warnings

.gitignore
This isn't very interesting, just wanted to check this looked sensible.
Merging into your branch for now.
=> Reviewer RKD: Add gitignores

metaswitch/common/pdlogs.py
Ellie,
Please can you review my changes to PD logging, which are required for corresponding changes in crest?
Thanks,
Matt
=> [Reviewer: Ellie] Add LOG_WARNING and CL_CREST_ID

metaswitch/common/utils.py
Part of the fix to https://github.com/Metaswitch/clearwater-etcd/issues/218 .
=> [Reviewer: Alex] Add a utility function to create and lock a pidfile

metaswitch/common/pdlogs.py
Adds the PDlog value for the new queue manager
=> [Reviewer: Andy] Add PDlog values for the queue manager

metaswitch/common/alarms_parser.py
Fixes https://github.com/Metaswitch/clearwater-etcd/issues/214
=> [Reviewer: Rob] iss214: Adds comment explaining alarm severity/state mapping

metaswitch/common/alarms.py
Rob - I think this sums up the conversation we just had. Any comments before I merge?
=> [Reviewer RKD] Add a comment to alarms.py.

setup.py
Pin third party code to a known version
=> [No reviewer] Add explicit version constraints

metaswitch/common/test/alarms_parser.py, metaswitch/common/test/test_missing_mandatory_value.json
I've fixed this up after missing the merge issue. You've been tinkering in this area recently.
=> [Reviewer Graeme] Fix up issue with changed parsing logic missed in test.

metaswitch/common/test/alarms_parser.py, metaswitch/common/test/test_missing_action_value.json, metaswitch/common/test/test_missing_cause_value.json, metaswitch/common/test/test_missing_effect_value.json, metaswitch/common/test/test_missing_severity_value.json
I've added tests to check that each of the new fields is indeed mandatory.
=> Reviewer CNE: Add UTs for new mandatory alarm fields

metaswitch/common/alarms.py, metaswitch/common/test/test_alarms.py
Ellie, can you please review my attached fixes. The threading code here is a little fragile, with plenty of co-operation, but I don't see a simple alternative.
@johadalin you've been reviewing the rest of this so please take a look.
=> [Reviewer Ellie] Build errors

metaswitch/common/test/test_alarms.py
I've skipped the tests and noted the issue tracking the problem.
=> [Reviewer Graeme] Skip failing tests and link to tracking issue.

metaswitch/common/test/test_alarms.py
I skipped the wrong one :disappointed:
=> [#NoReview] Skip the right unit tests.

metaswitch/common/pdlogs.py
Update the log ranges to keep in sync with the list in cpp-common.
=> [Reviewer: EM] Update reserved log ranges

Makefile, metaswitch/common/alarms_parser.py, metaswitch/common/alarms_to_dita.py, metaswitch/common/dita_content.py, metaswitch/common/test/alarms_parser.py, metaswitch/common/test/test_valid_alarms.dita, metaswitch/common/test/test_valid_alarms.json
Add support for parsing alarms files and generating a DITA document that describes them.
=> [Reviewer: Ellie] Alarms to dita

Makefile, metaswitch/common/alarms_parser.py, metaswitch/common/alarms_to_dita.py, metaswitch/common/dita_content.py, metaswitch/common/stats_to_dita.py, metaswitch/common/test/test_valid_alarms.dita
Merge docs auto-generation fixes into Clearwater Core V10.
These have been merged into dev, reviewed by Mat Meredith.
=> Docs autogen

Makefile, metaswitch/common/alarms_parser.py, metaswitch/common/alarms_to_dita.py, metaswitch/common/dita_content.py, metaswitch/common/stats_to_dita.py, metaswitch/common/test/test_valid_alarms.dita
Catch-up merge to clean-up docs_autogen changes.
=> Release 114 fixes

metaswitch/common/generate_stats_csv.py
Tested by running over script and ensuring that Project Clearwater rows were remove.
=> Update logic to skip Project Clearwater only MIBs.

metaswitch/common/utils.py
Put back function that was still in use
=> [No reviewer] Fix up removal

.gitmodules, Makefile
Make Analysis command now passes fine
=> Build infra submodule

Makefile
Still seeing the problem referenced in https://github.com/Metaswitch/python-common/pull/110 on some systems
=> [No reviewer] Upgrade pip further

Makefile
https://github.com/Metaswitch/python-common/pull/111 for building the common wheel as well.
=> [No reviewer] Upgrade pip for common wheel

metaswitch/common/logging_config.py, metaswitch/common/test/test_logging.py
I've live tested the new `configure_syslog()` function with the `cw-config` stuff and it seems to work fine. I haven't tested that it doesn't change the behaviour of `configure_logging()` though.
=> [Reviewer: Seb] Adds the ability to send python logs to syslog

metaswitch/common/pdlogs.py
Fallout from https://github.com/Metaswitch/cpp-common/pull/702
=> [Reviewer: Seb] Add Rogers PD log range
